### ISSUE TITLE
ci(appveyor): build and test on windows

### ISSUE THREAD

**Issue by gregswindle** [commonality/archetypes#18]
:bulb: __TIP:__ Select the "Preview" Tab to help read these instructions.

## 1. Issue type
> Type the letter "x" in the "checkbox" the best describe this issue.

- [ ] __CIr:__   I want to discuss something else.

## 2. User story summary
> Describe what you want to accomplish and in what role/capacity, and why it's important to you.

> __EXAMPLE:__
> As a Job Applicant,
> I want to submit my resume
> In order to be considered for a job opening.

As a {role},
I must/need/want/should {do something}
In order to {achieve value}.

## 3. Acceptance criteria
> Replace the examples below with your own imperative, "true/false" statements for the __behavior you expect__ to see, or the behavior that __would__ be true if there were no errors (for defects).

- [ ] 1. Job Applicants receive a confirmation email after they submit their resumes.
- [ ] 2. An Applicant's resume information isn't lost when errors occur.
- [ ] 3. {criterion-three}
- [ ] 4. {criterion-four}

## appveyor.yml

```yaml
install:
  - ps: Install-Product node '7'
  - npm install -g npm --silent --quiet
  - npm install --silent --quiet

platform:
  - x86
  - x64

build: off

test_script:
  - node --version
  - npm --version
  - npm test
```
